### ISSUE TITLE
IncompatibleClassChangeError when opening creative inventory 

### ISSUE THREAD

**Issue by MMK21Hub** [Minenash/Creative-Library#2]
When pressing E to open my inventory, the game immediately crashed.

[crash-2021-08-19_09.05.08-client.txt](https://github.com/Minenash/Creative-Library/files/7012756/crash-2021-08-19_09.05.08-client.txt)

**Comment by floofyneko69** [comment]
Your crash text file mentions that you used version 1.17.1, and Creative Library is not yet ready for 1.17 just yet, it's best to continue in 1.16.5 at the latest if you want to use Creative Library until a 1.17 compatible jar is ready to be used

**Comment by MMK21Hub** [comment]
Thanks, that explains the missing Modrinth release. Thanks for the response; I look forward to playing with Creative Library in 1.17 once it's ready.
